### ISSUE TITLE
$unset test will always pass

### ISSUE THREAD

**Issue by wilfredjonathanjames** [lgandecki/modifyjs#1]
Your `$unset` test will always pass.

```
expect(updatedObject).toEqual(updatedObject);
```

https://github.com/lgandecki/modifyjs/blob/HEAD/src/modify.test.js#L202

Noticed because `mongo-mock` `$unset` behaviour is broken, and they rely on `modifyjs`.

**Comment by lgandecki** [comment]
Thanks! Fixed in #2 .
